name: Terraform CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    inputs:
      do_destroy:
        description: "Run terraform destroy"
        type: boolean
        default: false
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Destroy (auto)
        if: >
          (github.event_name == 'push' &&
           (vars.AUTO_DESTROY == 'true' ||
            contains(github.event.head_commit.message, '[destroy]'))) ||
          (github.event_name == 'workflow_dispatch' &&
           (inputs.action == 'destroy'))
        run: terraform destroy -auto-approve -input=false -lock-timeout=20m -refresh=true -var-file=envs/prod.tfvars
